name: Build dump978-fa

on: [ push, pull_request ]

jobs:
  build:
    name: Build dump978-fa
    strategy:
      fail-fast: false
      matrix:
        image:
          - ubuntu-24.04
          - ubuntu-24.04-arm
        cc:
          - gcc-10
          - gcc-12
          - gcc-14
        include:
          - cc: gcc-10
            cxx: g++-10
          - cc: gcc-12
            cxx: g++-12
          - cc: gcc-14
            cxx: g++-14
    runs-on: ${{ matrix.image }}
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Install build prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends debhelper libboost-system-dev libboost-program-options-dev libboost-regex-dev libboost-filesystem-dev libsoapysdr-dev ${{ matrix.cc }} ${{ matrix.cxx }}
      - name: Build it
        run: |
          make all
      - name: Run tests
        run: |
          make test
